### ISSUE TITLE
Start/stop wavefrontReporter function

### ISSUE THREAD

**Issue by sliu2013** [wavefrontHQ/go-metrics-wavefront#11]
According to README.md, currently we use goroutine or a long-lasting func() to have the wavefrontReporter (either proxy or direct-ingestion)
```
  go wavefront.WavefrontDirect(metrics.DefaultRegistry, 5*time.Second, hostTags, "direct.prefix", server, token)
```

I need to use channel (maybe considered as a hacky way) to stop the wavefrontReporter. It would be nice if we can stop the reporter by calling a stop() function. Also, maybe we can consider to have some abstraction, so the users only need to call wavefront.WavefrontReporter() instead of WavefrontDirect and WavefrontProxy respectively.

**Comment by vikramraman** [comment]
Addressed in the latest refactoring.
