### ISSUE TITLE
Split repository

### ISSUE THREAD

**Issue by axpira** [wavefrontHQ/go-metrics-wavefront#14]
The idea of support tags in go-metrics is very good.
So why don't split this repository in two?
Because who want to use only go-metrics with tags can use.

**Comment by vikramraman** [comment]
Hi @axpira. Do you wish to create a metric without any metric specific tags?

I think we can handle that without splitting the repository. You bring up a good point, appears the `EncodeKey` assumes tags are always non-empty: https://github.com/wavefrontHQ/go-metrics-wavefront/blob/e86b11d2e81bbf4e48f1fde1fe8ad5e4b8b5e40e/reporting/utils.go#L10. We should be able to fix that to handle empty tags. So you can just call `RegisterMetric(name, metric, nil)`.

Would that fix your issue?

**Comment by vikramraman** [comment]
Resolved with https://github.com/wavefrontHQ/go-metrics-wavefront/commit/a8ea12bf9968f602e17d9db726368c18bad6677f
